# Generated by Django 5.2.7 on 2025-10-27 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('objects_detected', models.TextField(blank=True)),
                ('confidence_scores', models.TextField(blank=True)),
                ('detection_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
